### ISSUE TITLE
[12] Error during clean installation 

### ISSUE THREAD

**Issue by mita4kata** [JayVora-SerpentCS/fleet_management#20]
Dear Developers, 
, after installation of Odoo Fleet Operation App on clean  Odoo 12 CE without demo data,  we are getting an issue - missing menus, icons and functionalities. 

Odoo12 CE  installed on  Windows by latest Odoo.exe installer and all the required modules.

Below is the part of odoo.log with debug info. 

2019-05-05 12:30:19,371 3772 ERROR fleet odoo.sql_db: bad query: b"\n INSERT INTO ir_model_data (module, name, model, res_id, noupdate, date_init, date_update)\n VALUES ('fleet_operations', 'access_service_task_user', 'ir.model.access', 421, false, now() at …………………...

DO UPDATE SET date_update=(now() at time zone 'UTC') \n “

 ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time HINT: Ensure that no rows proposed for insertion within the same command have duplicate constrained values. 2019-05-05 12:30:19,371 3772

 ERROR fleet odoo.addons.base.models.ir_model: Failed to insert ir_model_data ('fleet_operations', 'access_service_task_user', 'ir.model.access', 421, False)

Thank you !

**Comment by YogendrasinhChavda** [comment]
Hello @mita4kata,
Good Afternoon!

We checked the Fleet Operation App on clean Odoo 12 CE Version by creating a fresh database with Demo data and Without Demo data. 
It's working fine, I mean we are not able to replicate the same issue.
Please take the latest update of the fleet 12.0 and check by upgrading the modules.

Framework Information:
Odoo CE 12.0
Ubuntu 18.04.02 LTS

Thanks

**Comment by mita4kata** [comment]
Hello, 
after updating to the latest version the installation is done without errors , but again there are few issues 

  - The Vehicle state menu is missing from the Configuration Pattern Menu;
  - The work order form has a bug ; 
as attachment you could find few screenshots and Odoo.log


[Odoo Server Error.txt](https://github.com/JayVora-SerpentCS/fleet_management/files/3149103/Odoo.Server.Error.txt)

  
[odoo.log](https://github.com/JayVora-SerpentCS/fleet_management/files/3149089/odoo.log)

![No_Vehicle_Status_on_The_Fleet_Menu](https://user-images.githubusercontent.com/50295420/57242310-dd518780-703b-11e9-8552-628e9f5d1c08.PNG)
![Work Order](https://user-images.githubusercontent.com/50295420/57242314-e0e50e80-703b-11e9-83a5-6471e08b258b.PNG)

**Comment by YogendrasinhChavda** [comment]
Hello @mita4kata ,

**1)**  The Vehicle state menu is missing from the Configuration Pattern Menu.

We are not using the base vehicle status menus in fleet operations module, we add our own state to manage fleet operations and fleet rent flow. 

We hide that menu and some others menu using One group called "Hide Menu", those who is no longer to use in flow, but if you want to see that menu then you can Active that from the User Form view.

See the below screenshot:
You have to go in user form view and Assign the "Hide Menu".

![usr_hide_menu_group](https://user-images.githubusercontent.com/11770935/57281239-35ce6680-70c8-11e9-9b7c-86394aa204ed.png)

**2)** The work order form has a bug ;
as attachment you could find few screenshots and Odoo.log

Please take latest updated code from the branch and check it, that issue is resolved.

**3)** About your sent second screenshot.
        We attached screen shots here and described those fields.

	1. Next Odometer Increment:
		When we close the work order. System will ask to set next odometer increment. 
                We need to set that from the configuration, after that ask to set Last odomenter increment if is 
                 not set. 
		Based on the last odometer and next service odometer we calculate the Next Odometer. 
                It is a compute field so no need to set value manually 
		Next Odometer Value = Last Odometer + Odometer Increment (Comes from Configuration)

	2. Closed By:
		Closed by field shown the responsible person who the closed this work order. 
                It's take a default value to which user is currently logged in.

	3. Next service date:
		It is also compute Field. when we close work order system ask to add "next service days". 
                Based on next service days, System calculate the next service date for work order.
		Next Service Date = current date + Next Service Dates (Comes from Configuration)

![wo_ss](https://user-images.githubusercontent.com/11770935/57282034-dbcea080-70c9-11e9-87f2-7cea34635faf.png)


![wo_cong](https://user-images.githubusercontent.com/11770935/57282059-e9842600-70c9-11e9-9a7c-17626f73fe6e.png)


Please take latest updated code from the branch and check it.

Thank you.
